name: perl-Config-Extend-MySQL
upstream: http://search.cpan.org/dist/Config-Extend-MySQL/
description: Extend your favourite .INI parser module to read MySQL configuration
  file
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: readonly
  create_from: master
- name: openEuler-24.03-LTS-Next
  type: protected
  create_from: master
- name: openEuler-24.03-LTS
  type: protected
  create_from: openEuler-24.03-LTS-Next
- name: openEuler-24.09
  type: protected
  create_from: master
type: public
