name: devstation-config
description: config and shortcut for devstation
upstream: https://gitee.com/openeuler/devstation-config.git
branches:
- name: master
  type: protected
- name: openEuler-24.09
  type: protected
  create_from: master
type: public
