name: python-pydantic-settings
description: Settings management using pydantic
upstream: https://github.com/pydantic/pydantic-settings
branches:
- name: master
  type: protected
- name: openEuler-25.03
  type: protected
  create_from: master
- name: openEuler-24.03-LTS-Next
  type: protected
  create_from: master
- name: openEuler-24.03-LTS-SP2
  type: protected
  create_from: openEuler-24.03-LTS-Next
type: public
