name: scf-security
description: A Lib that provides TLS security specification-compliant, and shields the differences between HiTLS, openSSL and other TSL protocol. 
branches:
- name: master
  type: protected
type: public
