name: fcitx5-configtool
description: Configuration tools used by fcitx5
upstream: https://github.com/fcitx/fcitx5-configtool
branches:
- name: master
  type: protected
- name: openEuler-24.03-LTS-Next
  type: protected
  create_from: master
- name: openEuler-24.09
  type: protected
  create_from: master
- name: openEuler-25.03
  type: protected
  create_from: master
- name: openEuler-25.09
  type: protected
  create_from: master
type: public
