name: plasma-systemsettings
description: Control center to configure your Plasma Desktop
upstream: https://github.com/KDE/systemsettings
branches:
- name: master
  type: protected
- name: openEuler-24.03-LTS-Next
  type: protected
  create_from: master
type: public
