name: agent-skills
description: 'Agent skills made by openEuler community to provide a smooth vibe coding experience for developers.'
branches:
- name: master
  type: protected
- name: cve-agent-team
  type: protected
type: public