name: scf-security
description: A lib that provides TLS security specification-compliant, and shields the differences between HiTLS, openSSL and other TSL protocols. 
branches:
- name: master
  type: protected
type: public
