name: scf-security
description: A lib that provides a TLS communication security programming framework.  
upstream: https://atomgit.com/openeuler/scf-security
branches:
- name: master
  type: protected
type: public
