name: prometheus-cpp
description: 'Prometheus-cpp aims to enable Metrics-Driven Development for C++ services'
upstream: https://github.com/jupp0r/prometheus-cpp
branches: 
- name: master
  type: protected
- name: openEuler-22.03-LTS-Next
  type: protected
  create_from: master
- name: openEuler-22.03-LTS-SP4
  type: protected
  create_from: openEuler-22.03-LTS-Next
type: public
