name: clearpath_config
description: 'Clearpath Configuration YAML Parser and Writer'
upstream: https://github.com/clearpathrobotics/clearpath_config.git
platform: gitee
branches:
- name: master
  type: protected
type: public