name: dynamic_reconfigure
description: The dynamic_reconfigure package provides a means to update parameters
  at runtime without having to restart the node.
upstream: https://github.com/ros/dynamic_reconfigure
branches:
- name: master
  type: protected
- name: openEuler-20.03-LTS-Next
  type: readonly
  create_from: master
- name: noetic
  type: protected
  create_from: master
- name: Multi-Version_ros-noetic_openEuler-24.03-LTS-Next
  type: protected
  create_from: noetic
- name: Multi-Version_ros-noetic_openEuler-24.03-LTS
  type: protected
  create_from: Multi-Version_ros-noetic_openEuler-24.03-LTS-Next
- name: Multi-Version_ros-noetic_openEuler-24.09
  type: protected
  create_from: noetic
type: public
